CREATE TABLE KTMCF10_VIN (
	F10_VIN_C VARCHAR(17) NOT NULL,
	F10_TMC605_STATUS_CODE_R NUMERIC(3) NOT NULL,
	F10_TMC605_STATUS_TYPE_CODE_R NUMERIC(3) NOT NULL,
	F10_TMC605_STATUS_TYPE_ESB_VEHICLE_AREA_CODE_C CHAR(3) NOT NULL,
	F10_TMC605_STATUS_TYPE_COUNTRY_CODE_C CHAR(3) NOT NULL,
	F10_CREATE_USER_C VARCHAR(5) NOT NULL,
	F10_CREATE_S DATETIME NOT NULL,
	F10_UPDATE_USER_C VARCHAR(5),
	F10_UPDATE_S DATETIME,
	F10_UPDATE_PROCESS_N VARCHAR(20),
	F10_CVVG_S DATETIME NOT NULL,
	F10_FACTORY_WARRANTY_END_S DATETIME NOT NULL,
	CONSTRAINT KTMCF10_VIN_pk PRIMARY KEY (F10_VIN_C)
)