CREATE TABLE KTMCF21_CONTRATCT_X_VIN (
	F21_CONTRACT_X_VIN_K INT NOT NULL AUTO_INCREMENT,
	F21_F20_CONTRACT_C NUMERIC(10) NOT NULL,
	F21_F10_VIN_C VARCHAR(17) NOT NULL,
	F21_UPDATE_PROCESS_N VARCHAR(20),
	F21_UPDATE_USER_C VARCHAR(5),
	F21_CREATE_USER_C VARCHAR(5) NOT NULL,
	F21_UPDATE_S DATETIME,
	F21_CREATE_S DATETIME NOT NULL,
	F21_INITIAL_KM NUMERIC(10,3) NOT NULL,
	F21_FINAL_KM NUMERIC(10,3) NOT NULL,
	CONSTRAINT KTMCF21_CONTRATCT_X_VIN_pk PRIMARY KEY (F21_CONTRACT_X_VIN_K, F21_F20_CONTRACT_C, F21_F10_VIN_C)
)